const express = require('express')
const cors=require('cors')
const app = express()
const router = require('./router')
app.use( cors())
app.use( router)
app.listen(80, () => console.log(`Example app listening on http://127.0.0.1`))
